server:
  port: 8082
spring:
  profiles:
    active: @activatedProperties@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: /mapper/*.xml
  type-aliases-package: com.yzz.practice_mybatisplus.entity
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
  #    配置自增主键的策略
    key-generator: com.baimidou.mybatisplus.incrementer.OracleKeyGenerator
  #    配置这两个属性以后，删除数据的时候不会真的删除库里的logic_flag这个字段
  #    只是查询的时候不显示了
  #    需要增加以下两个值，所以需要对象表要有这个字段
  #    logic-delete-value: 1
  #    logic-not-delete-value: -1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    # 日志配置到标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.yzz.practice_mybatisplus.dao: trace

pagehelper:
  # dialect: ①
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
  helper-dialect: mysql
  # 上面数据库设置后，下面的设置为true不会改变上面的结果（默认为true）
  auto-dialect: true
  page-size-zero: false # ②
  reasonable: true # ③
  # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。（一般用不着）
  offset-as-page-num: false
  # 默认值为 false，RowBounds是否进行count查询（一般用不着）
  row-bounds-with-count: false
  #params: ④
  #support-methods-arguments: 和params配合使用，具体可以看下面的讲解
  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
  auto-runtime-dialect: false # ⑤
  # 与auto-runtime-dialect配合使用
  close-conn: true
  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
  default-count: false
  #dialect-alias: ⑥