spring:
  profiles: home
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.23.3:3306/db1?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true
    username: root
    password: Rootroot123!
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 1
      maxActive: 50